mqtt:
    
  - sensor:
  
    - name: FB_0001_Battery_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Voltage
    - name: FB_0001_Battery_Current
      state_topic: solar/felicity_battery/0001/Battery_Current
      unit_of_measurement: A
      state_class: measurement
      device_class: current
      unique_id: FB_0001_Battery_Current
    - name: FB_0001_Battery_Power
      state_topic: solar/felicity_battery/0001/Battery_Power
      unit_of_measurement: W
      state_class: measurement
      device_class: power
      unique_id: FB_0001_Battery_Power
    - name: FB_0001_Battery_SOC
      state_topic: solar/felicity_battery/0001/Battery_SOC
      unit_of_measurement: '%'
      state_class: measurement
      device_class: battery
      unique_id: FB_0001_Battery_SOC
      
    - name: FB_0001_Battery_Temperature_01
      state_topic: solar/felicity_battery/0001/Battery_Temperature_01
      unit_of_measurement: 째C
      state_class: measurement
      device_class: temperature
      unique_id: FB_0001_Battery_Temperature_01
    - name: FB_0001_Battery_Temperature_02
      state_topic: solar/felicity_battery/0001/Battery_Temperature_02
      unit_of_measurement: 째C
      state_class: measurement
      device_class: temperature
      unique_id: FB_0001_Battery_Temperature_02
    - name: FB_0001_Battery_Temperature_03
      state_topic: solar/felicity_battery/0001/Battery_Temperature_03
      unit_of_measurement: 째C
      state_class: measurement
      device_class: temperature
      unique_id: FB_0001_Battery_Temperature_03
    - name: FB_0001_Battery_Temperature_04
      state_topic: solar/felicity_battery/0001/Battery_Temperature_04
      unit_of_measurement: 째C
      state_class: measurement
      device_class: temperature
      unique_id: FB_0001_Battery_Temperature_04
      
    - name: FB_0001_Battery_Cell_01_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_01_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_01_Voltage
    - name: FB_0001_Battery_Cell_02_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_02_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_02_Voltage
    - name: FB_0001_Battery_Cell_03_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_03_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_03_Voltage
    - name: FB_0001_Battery_Cell_04_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_04_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_04_Voltage
    - name: FB_0001_Battery_Cell_05_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_05_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_05_Voltage
    - name: FB_0001_Battery_Cell_06_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_06_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_06_Voltage
    - name: FB_0001_Battery_Cell_07_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_07_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_07_Voltage
    - name: FB_0001_Battery_Cell_08_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_08_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_08_Voltage
    - name: FB_0001_Battery_Cell_09_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_09_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_09_Voltage
    - name: FB_0001_Battery_Cell_10_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_10_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_10_Voltage
    - name: FB_0001_Battery_Cell_11_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_11_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_11_Voltage
    - name: FB_0001_Battery_Cell_12_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_12_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_12_Voltage
    - name: FB_0001_Battery_Cell_13_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_13_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_13_Voltage
    - name: FB_0001_Battery_Cell_14_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_14_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_14_Voltage
    - name: FB_0001_Battery_Cell_15_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_15_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_15_Voltage
    - name: FB_0001_Battery_Cell_16_Voltage
      state_topic: solar/felicity_battery/0001/Battery_Cell_16_Voltage
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
      unique_id: FB_0001_Battery_Cell_16_Voltage